import type {
  Assessment,
  HistoricalMatch,
  ImpactModule,
  EffortEstimation,
  JiraStory,
  CodeImpact,
  Risk,
  Dependency,
  DashboardStats,
  MonthlyAnalytics,
  User,
  Notification,
  AssessmentResult,
} from '@/types/assessment';

// Current user
export const currentUser: User = {
  id: 'user-1',
  name: 'Markus Chen',
  email: 'markus.chen@elevance.com',
  avatar: '/avatars/markus.jpg',
  role: 'analyst',
};

// Dashboard Statistics
export const dashboardStats: DashboardStats = {
  activeAssessments: 12,
  totalProjects: 147,
  pendingReviews: 5,
  avgAccuracy: 89.75,
};

// Monthly Analytics for charts
export const monthlyAnalytics: MonthlyAnalytics[] = [
  { month: 'Jan', projectsDone: 45, projectsTasks: 52, projectsGoal: 50 },
  { month: 'Feb', projectsDone: 52, projectsTasks: 48, projectsGoal: 50 },
  { month: 'Mar', projectsDone: 61, projectsTasks: 55, projectsGoal: 55 },
  { month: 'Apr', projectsDone: 58, projectsTasks: 62, projectsGoal: 60 },
  { month: 'May', projectsDone: 137, projectsTasks: 123, projectsGoal: 84 },
  { month: 'Jun', projectsDone: 72, projectsTasks: 68, projectsGoal: 70 },
  { month: 'Jul', projectsDone: 65, projectsTasks: 70, projectsGoal: 70 },
  { month: 'Aug', projectsDone: 78, projectsTasks: 75, projectsGoal: 75 },
  { month: 'Sep', projectsDone: 82, projectsTasks: 80, projectsGoal: 80 },
];

// Sample Assessments
export const assessments: Assessment[] = [
  {
    id: 'assess-1',
    title: 'Member Portal Authentication Upgrade',
    description: 'Implement OAuth 2.0 and SSO integration for the member portal to enhance security and user experience.',
    status: 'completed',
    createdAt: new Date('2024-11-15'),
    updatedAt: new Date('2024-12-01'),
    epicId: 'EPIC-2341',
    epicUrl: 'https://jira.elevance.com/browse/EPIC-2341',
    confidenceScore: 92,
    createdBy: 'user-1',
    assignedTo: 'user-2',
  },
  {
    id: 'assess-2',
    title: 'Claims Processing Automation',
    description: 'Automate claims adjudication workflow using ML models for faster processing and reduced manual review.',
    status: 'analyzing',
    createdAt: new Date('2024-12-10'),
    updatedAt: new Date('2024-12-20'),
    epicId: 'EPIC-2456',
    confidenceScore: 78,
    createdBy: 'user-1',
  },
  {
    id: 'assess-3',
    title: 'Provider Directory Search Enhancement',
    description: 'Add advanced filtering, geo-location search, and real-time availability for provider directory.',
    status: 'draft',
    createdAt: new Date('2024-12-18'),
    updatedAt: new Date('2024-12-18'),
    confidenceScore: 0,
    createdBy: 'user-1',
  },
  {
    id: 'assess-4',
    title: 'Mobile App Prescription Refill Feature',
    description: 'Enable members to request prescription refills directly through the mobile app with pharmacy integration.',
    status: 'completed',
    createdAt: new Date('2024-10-05'),
    updatedAt: new Date('2024-11-20'),
    epicId: 'EPIC-2198',
    confidenceScore: 95,
    createdBy: 'user-3',
    assignedTo: 'user-1',
  },
  {
    id: 'assess-5',
    title: 'Benefits Eligibility Real-time Check',
    description: 'Integrate real-time eligibility verification API for instant benefits confirmation at point of service.',
    status: 'completed',
    createdAt: new Date('2024-09-12'),
    updatedAt: new Date('2024-10-28'),
    epicId: 'EPIC-2089',
    confidenceScore: 88,
    createdBy: 'user-2',
  },
];

// Historical Matches for similarity analysis
export const historicalMatches: HistoricalMatch[] = [
  {
    id: 'hist-1',
    epicId: 'EPIC-1892',
    epicName: 'Enterprise SSO Implementation',
    epicDescription: 'Implemented SAML 2.0 based SSO across all internal applications with MFA support.',
    similarityScore: 94,
    technologies: ['OAuth 2.0', 'SAML', 'Azure AD', 'React', 'Node.js'],
    modules: ['Authentication', 'User Management', 'Session Handling'],
    actualEffort: 480,
    estimatedEffort: 520,
    completionStatus: 'completed',
    completedDate: new Date('2024-06-15'),
    teamSize: 5,
    lessonsLearned: 'Early integration testing with identity provider saved significant debugging time.',
  },
  {
    id: 'hist-2',
    epicId: 'EPIC-1654',
    epicName: 'Customer Portal Auth Refresh',
    epicDescription: 'Migrated legacy session-based auth to JWT tokens with refresh token rotation.',
    similarityScore: 87,
    technologies: ['JWT', 'React', 'Spring Boot', 'PostgreSQL'],
    modules: ['Authentication', 'API Gateway', 'Token Management'],
    actualEffort: 320,
    estimatedEffort: 280,
    completionStatus: 'completed',
    completedDate: new Date('2024-03-20'),
    teamSize: 4,
    lessonsLearned: 'Token rotation complexity was underestimated. Add buffer for security features.',
  },
  {
    id: 'hist-3',
    epicId: 'EPIC-1423',
    epicName: 'Mobile App Biometric Login',
    epicDescription: 'Added fingerprint and Face ID support for mobile app authentication.',
    similarityScore: 72,
    technologies: ['React Native', 'Biometrics API', 'Keychain', 'Node.js'],
    modules: ['Mobile Auth', 'Secure Storage', 'Session Management'],
    actualEffort: 240,
    estimatedEffort: 200,
    completionStatus: 'completed',
    completedDate: new Date('2024-01-10'),
    teamSize: 3,
  },
  {
    id: 'hist-4',
    epicId: 'EPIC-1987',
    epicName: 'Provider Portal MFA Rollout',
    epicDescription: 'Implemented multi-factor authentication for provider portal using TOTP and SMS.',
    similarityScore: 68,
    technologies: ['TOTP', 'Twilio', 'Angular', 'Java'],
    modules: ['MFA', 'SMS Gateway', 'User Preferences'],
    actualEffort: 160,
    estimatedEffort: 180,
    completionStatus: 'completed',
    completedDate: new Date('2024-08-05'),
    teamSize: 3,
  },
  {
    id: 'hist-5',
    epicId: 'EPIC-2034',
    epicName: 'API Gateway Authentication',
    epicDescription: 'Centralized authentication at API gateway level with rate limiting and token validation.',
    similarityScore: 65,
    technologies: ['Kong', 'OAuth 2.0', 'Redis', 'Kubernetes'],
    modules: ['API Gateway', 'Rate Limiting', 'Token Validation'],
    actualEffort: 280,
    estimatedEffort: 300,
    completionStatus: 'completed',
    completedDate: new Date('2024-07-22'),
    teamSize: 4,
  },
];

// Impacted Modules
export const functionalModules: ImpactModule[] = [
  {
    id: 'fm-1',
    name: 'Member Login Flow',
    type: 'functional',
    impactSeverity: 'HIGH',
    rationale: 'Core authentication flow will be completely redesigned to support OAuth 2.0 authorization code flow with PKCE.',
    dependencies: ['User Session Management', 'Profile Service'],
    estimatedEffort: 80,
    owner: 'Auth Team',
    tddSection: 'TDD-AUTH-001',
    included: true,
  },
  {
    id: 'fm-2',
    name: 'Session Management',
    type: 'functional',
    impactSeverity: 'HIGH',
    rationale: 'Token-based sessions replace server-side sessions. Requires refresh token implementation.',
    dependencies: ['Member Login Flow', 'API Gateway'],
    estimatedEffort: 60,
    owner: 'Platform Team',
    tddSection: 'TDD-AUTH-002',
    included: true,
  },
  {
    id: 'fm-3',
    name: 'Password Reset',
    type: 'functional',
    impactSeverity: 'MEDIUM',
    rationale: 'Password reset flow needs to integrate with new identity provider for secure reset links.',
    dependencies: ['Email Service', 'Member Login Flow'],
    estimatedEffort: 24,
    owner: 'Auth Team',
    tddSection: 'TDD-AUTH-003',
    included: true,
  },
  {
    id: 'fm-4',
    name: 'Remember Me Feature',
    type: 'functional',
    impactSeverity: 'LOW',
    rationale: 'Extend refresh token lifetime for trusted devices. Minor change to token configuration.',
    dependencies: ['Session Management'],
    estimatedEffort: 8,
    owner: 'Auth Team',
    included: true,
  },
  {
    id: 'fm-5',
    name: 'Logout & Session Termination',
    type: 'functional',
    impactSeverity: 'MEDIUM',
    rationale: 'Implement proper token revocation and SSO logout propagation across all connected apps.',
    dependencies: ['Session Management', 'SSO Integration'],
    estimatedEffort: 16,
    owner: 'Auth Team',
    tddSection: 'TDD-AUTH-004',
    included: true,
  },
];

export const technicalModules: ImpactModule[] = [
  {
    id: 'tm-1',
    name: 'Identity Provider Integration',
    type: 'technical',
    impactSeverity: 'HIGH',
    rationale: 'New integration with Azure AD B2C for enterprise SSO. Requires OIDC protocol implementation.',
    dependencies: ['API Gateway', 'User Service'],
    estimatedEffort: 120,
    owner: 'Platform Team',
    tddSection: 'TDD-TECH-001',
    included: true,
  },
  {
    id: 'tm-2',
    name: 'Token Service',
    type: 'technical',
    impactSeverity: 'HIGH',
    rationale: 'New microservice for JWT token generation, validation, and refresh token rotation.',
    dependencies: ['Redis Cache', 'Identity Provider Integration'],
    estimatedEffort: 80,
    owner: 'Platform Team',
    tddSection: 'TDD-TECH-002',
    included: true,
  },
  {
    id: 'tm-3',
    name: 'API Gateway Auth Module',
    type: 'technical',
    impactSeverity: 'HIGH',
    rationale: 'Update Kong gateway plugins for OAuth 2.0 token introspection and validation.',
    dependencies: ['Token Service'],
    estimatedEffort: 40,
    owner: 'Infrastructure Team',
    tddSection: 'TDD-TECH-003',
    included: true,
  },
  {
    id: 'tm-4',
    name: 'Database Schema Updates',
    type: 'technical',
    impactSeverity: 'MEDIUM',
    rationale: 'Add tables for refresh tokens, device trust, and audit logging.',
    dependencies: [],
    estimatedEffort: 16,
    owner: 'DBA Team',
    tddSection: 'TDD-TECH-004',
    included: true,
  },
  {
    id: 'tm-5',
    name: 'Frontend Auth SDK',
    type: 'technical',
    impactSeverity: 'MEDIUM',
    rationale: 'Update React authentication hooks and context for new OAuth flow.',
    dependencies: ['Token Service'],
    estimatedEffort: 32,
    owner: 'Frontend Team',
    tddSection: 'TDD-TECH-005',
    included: true,
  },
];

// Effort Estimation
export const effortEstimation: EffortEstimation = {
  totalDevHours: 476,
  totalQAHours: 120,
  totalDesignHours: 40,
  storyPoints: 89,
  confidenceScore: 85,
  breakdown: [
    { module: 'Identity Provider Integration', devHours: 120, qaHours: 30, designHours: 8 },
    { module: 'Token Service', devHours: 80, qaHours: 20, designHours: 4 },
    { module: 'Member Login Flow', devHours: 80, qaHours: 24, designHours: 16 },
    { module: 'Session Management', devHours: 60, qaHours: 16, designHours: 4 },
    { module: 'API Gateway Auth Module', devHours: 40, qaHours: 10, designHours: 0 },
    { module: 'Frontend Auth SDK', devHours: 32, qaHours: 8, designHours: 4 },
    { module: 'Password Reset', devHours: 24, qaHours: 6, designHours: 4 },
    { module: 'Database Schema Updates', devHours: 16, qaHours: 4, designHours: 0 },
    { module: 'Logout & Session Termination', devHours: 16, qaHours: 2, designHours: 0 },
    { module: 'Remember Me Feature', devHours: 8, qaHours: 0, designHours: 0 },
  ],
  historicalComparison: {
    averageEffort: 420,
    minEffort: 280,
    maxEffort: 520,
    sampleSize: 5,
  },
};

// Generated Jira Stories
export const jiraStories: JiraStory[] = [
  {
    id: 'story-1',
    title: 'Implement Azure AD B2C Integration',
    description: 'Set up Azure AD B2C tenant and configure OIDC endpoints for member authentication.',
    storyPoints: 13,
    priority: 'HIGH',
    type: 'Story',
    labels: ['auth', 'infrastructure', 'azure'],
    acceptanceCriteria: [
      'Azure AD B2C tenant configured with custom policies',
      'OIDC discovery endpoint accessible',
      'Test users created for development',
      'Documentation updated with setup steps',
    ],
    order: 1,
  },
  {
    id: 'story-2',
    title: 'Create Token Service Microservice',
    description: 'Develop new microservice for JWT token generation, validation, and refresh token management.',
    storyPoints: 13,
    priority: 'HIGH',
    type: 'Story',
    labels: ['auth', 'backend', 'microservice'],
    acceptanceCriteria: [
      'Token generation endpoint with configurable claims',
      'Token validation with signature verification',
      'Refresh token rotation implemented',
      'Redis integration for token blacklist',
      '90% unit test coverage',
    ],
    order: 2,
  },
  {
    id: 'story-3',
    title: 'Update Member Login UI for OAuth Flow',
    description: 'Redesign login page to support OAuth authorization code flow with PKCE.',
    storyPoints: 8,
    priority: 'HIGH',
    type: 'Story',
    labels: ['auth', 'frontend', 'ui'],
    acceptanceCriteria: [
      'Login redirects to Azure AD B2C',
      'Authorization code exchange handled',
      'Error states displayed appropriately',
      'Loading states during auth flow',
      'Accessibility compliance (WCAG 2.1 AA)',
    ],
    order: 3,
  },
  {
    id: 'story-4',
    title: 'Configure Kong Gateway OAuth Plugin',
    description: 'Update API Gateway to validate OAuth tokens on all protected routes.',
    storyPoints: 5,
    priority: 'HIGH',
    type: 'Story',
    labels: ['auth', 'infrastructure', 'kong'],
    acceptanceCriteria: [
      'OAuth 2.0 plugin configured',
      'Token introspection endpoint integrated',
      'Rate limiting per user configured',
      'Unauthorized requests return 401',
    ],
    order: 4,
  },
  {
    id: 'story-5',
    title: 'Implement Session Management with Refresh Tokens',
    description: 'Replace server-side sessions with JWT access tokens and refresh token rotation.',
    storyPoints: 8,
    priority: 'HIGH',
    type: 'Story',
    labels: ['auth', 'backend', 'security'],
    acceptanceCriteria: [
      'Access tokens expire in 15 minutes',
      'Refresh tokens rotate on each use',
      'Token family invalidation on reuse detection',
      'Secure cookie storage for refresh tokens',
    ],
    order: 5,
  },
  {
    id: 'story-6',
    title: 'Create React Auth Context and Hooks',
    description: 'Develop reusable authentication context and hooks for the frontend application.',
    storyPoints: 5,
    priority: 'MEDIUM',
    type: 'Story',
    labels: ['auth', 'frontend', 'react'],
    acceptanceCriteria: [
      'useAuth hook provides user state and auth methods',
      'AuthProvider wraps protected routes',
      'Automatic token refresh before expiry',
      'TypeScript types exported',
    ],
    order: 6,
  },
  {
    id: 'story-7',
    title: 'Update Password Reset Flow',
    description: 'Integrate password reset with Azure AD B2C self-service password reset.',
    storyPoints: 5,
    priority: 'MEDIUM',
    type: 'Story',
    labels: ['auth', 'frontend', 'azure'],
    acceptanceCriteria: [
      'Password reset redirects to B2C flow',
      'Custom branded reset experience',
      'Email notifications sent',
      'Audit logging for reset attempts',
    ],
    order: 7,
  },
  {
    id: 'story-8',
    title: 'Implement SSO Logout Propagation',
    description: 'Ensure logout terminates sessions across all connected applications.',
    storyPoints: 5,
    priority: 'MEDIUM',
    type: 'Story',
    labels: ['auth', 'sso', 'security'],
    acceptanceCriteria: [
      'Front-channel logout supported',
      'Back-channel logout webhook implemented',
      'All tokens revoked on logout',
      'User redirected to login page',
    ],
    order: 8,
  },
  {
    id: 'story-9',
    title: 'Database Migration for Auth Tables',
    description: 'Create database schema changes for refresh tokens and device trust.',
    storyPoints: 3,
    priority: 'MEDIUM',
    type: 'Task',
    labels: ['auth', 'database', 'migration'],
    acceptanceCriteria: [
      'Migration scripts created and tested',
      'Rollback scripts available',
      'Indexes optimized for query patterns',
      'Data retention policy documented',
    ],
    order: 9,
  },
  {
    id: 'story-10',
    title: 'Security Testing and Penetration Test',
    description: 'Conduct security review and penetration testing of new auth implementation.',
    storyPoints: 8,
    priority: 'HIGH',
    type: 'Spike',
    labels: ['auth', 'security', 'testing'],
    acceptanceCriteria: [
      'OWASP authentication checklist completed',
      'Penetration test report with no critical findings',
      'Token security best practices verified',
      'Security documentation updated',
    ],
    order: 10,
  },
];

// Code Impact Analysis
export const codeImpacts: CodeImpact[] = [
  {
    id: 'ci-1',
    repository: 'member-portal-frontend',
    filePath: 'src/auth/AuthContext.tsx',
    changeType: 'modified',
    language: 'TypeScript',
    estimatedLOC: 150,
    complexity: 'HIGH',
    description: 'Complete rewrite of authentication context for OAuth flow',
    gitlabUrl: 'https://gitlab.elevance.com/member-portal-frontend/-/blob/main/src/auth/AuthContext.tsx',
  },
  {
    id: 'ci-2',
    repository: 'member-portal-frontend',
    filePath: 'src/pages/Login.tsx',
    changeType: 'modified',
    language: 'TypeScript',
    estimatedLOC: 80,
    complexity: 'MEDIUM',
    description: 'Update login page to redirect to OAuth provider',
    gitlabUrl: 'https://gitlab.elevance.com/member-portal-frontend/-/blob/main/src/pages/Login.tsx',
  },
  {
    id: 'ci-3',
    repository: 'member-portal-frontend',
    filePath: 'src/auth/OAuthCallback.tsx',
    changeType: 'new',
    language: 'TypeScript',
    estimatedLOC: 60,
    complexity: 'MEDIUM',
    description: 'New component to handle OAuth callback and token exchange',
  },
  {
    id: 'ci-4',
    repository: 'auth-service',
    filePath: 'src/services/TokenService.ts',
    changeType: 'new',
    language: 'TypeScript',
    estimatedLOC: 200,
    complexity: 'HIGH',
    description: 'New token generation and validation service',
  },
  {
    id: 'ci-5',
    repository: 'auth-service',
    filePath: 'src/services/RefreshTokenService.ts',
    changeType: 'new',
    language: 'TypeScript',
    estimatedLOC: 150,
    complexity: 'HIGH',
    description: 'Refresh token rotation and family tracking',
  },
  {
    id: 'ci-6',
    repository: 'api-gateway-config',
    filePath: 'kong/plugins/oauth2-introspection.yaml',
    changeType: 'new',
    language: 'YAML',
    estimatedLOC: 40,
    complexity: 'LOW',
    description: 'Kong OAuth2 introspection plugin configuration',
  },
  {
    id: 'ci-7',
    repository: 'member-portal-backend',
    filePath: 'src/middleware/authMiddleware.ts',
    changeType: 'modified',
    language: 'TypeScript',
    estimatedLOC: 60,
    complexity: 'MEDIUM',
    description: 'Update middleware to validate JWT tokens',
  },
  {
    id: 'ci-8',
    repository: 'database-migrations',
    filePath: 'migrations/2024_12_auth_tokens.sql',
    changeType: 'new',
    language: 'SQL',
    estimatedLOC: 45,
    complexity: 'LOW',
    description: 'Create tables for refresh tokens and audit logs',
  },
];

// Risks
export const risks: Risk[] = [
  {
    id: 'risk-1',
    title: 'Azure AD B2C Service Dependency',
    description: 'Authentication flow depends on Azure AD B2C availability. Service outage would prevent all logins.',
    severity: 'HIGH',
    likelihood: 'LOW',
    category: 'technical',
    mitigation: 'Implement circuit breaker pattern with graceful degradation. Configure Azure B2C for high availability across regions.',
    owner: 'Platform Team',
    status: 'identified',
  },
  {
    id: 'risk-2',
    title: 'Token Migration Complexity',
    description: 'Existing users with active sessions need seamless migration to new token-based system.',
    severity: 'MEDIUM',
    likelihood: 'HIGH',
    category: 'technical',
    mitigation: 'Implement dual-auth support during transition period. Auto-migrate users on next login.',
    owner: 'Auth Team',
    status: 'mitigating',
  },
  {
    id: 'risk-3',
    title: 'Security Vulnerabilities in Token Handling',
    description: 'Improper token storage or transmission could expose user credentials.',
    severity: 'HIGH',
    likelihood: 'MEDIUM',
    category: 'technical',
    mitigation: 'Follow OWASP guidelines. Use httpOnly secure cookies. Conduct penetration testing before release.',
    owner: 'Security Team',
    status: 'identified',
  },
  {
    id: 'risk-4',
    title: 'Team Skill Gap in OAuth 2.0',
    description: 'Development team has limited experience with OAuth 2.0 and OIDC protocols.',
    severity: 'MEDIUM',
    likelihood: 'MEDIUM',
    category: 'resource',
    mitigation: 'Schedule OAuth training sessions. Engage external consultant for architecture review.',
    owner: 'Engineering Manager',
    status: 'mitigating',
  },
  {
    id: 'risk-5',
    title: 'Third-party Integration Delays',
    description: 'SSO integration with partner systems may face delays due to their release schedules.',
    severity: 'MEDIUM',
    likelihood: 'HIGH',
    category: 'schedule',
    mitigation: 'Early engagement with partner teams. Define clear API contracts upfront.',
    owner: 'Project Manager',
    status: 'identified',
  },
];

// Dependencies
export const dependencies: Dependency[] = [
  {
    id: 'dep-1',
    sourceModule: 'Member Login Flow',
    targetModule: 'Identity Provider Integration',
    type: 'downstream',
    description: 'Login flow initiates OAuth flow with identity provider',
    criticalPath: true,
  },
  {
    id: 'dep-2',
    sourceModule: 'Identity Provider Integration',
    targetModule: 'Token Service',
    type: 'downstream',
    description: 'IdP returns authorization code, Token Service exchanges for tokens',
    criticalPath: true,
  },
  {
    id: 'dep-3',
    sourceModule: 'Token Service',
    targetModule: 'API Gateway Auth Module',
    type: 'downstream',
    description: 'Gateway validates tokens using Token Service introspection endpoint',
    criticalPath: true,
  },
  {
    id: 'dep-4',
    sourceModule: 'Session Management',
    targetModule: 'Token Service',
    type: 'bidirectional',
    description: 'Session management relies on token lifecycle, Token Service tracks sessions',
    criticalPath: true,
  },
  {
    id: 'dep-5',
    sourceModule: 'Frontend Auth SDK',
    targetModule: 'Token Service',
    type: 'downstream',
    description: 'SDK calls Token Service for token refresh',
    criticalPath: false,
  },
];

// Notifications
export const notifications: Notification[] = [
  {
    id: 'notif-1',
    type: 'warning',
    title: 'Performance Decline Detected',
    message: "We have observed a decline in [Hermawan]'s performance over the past 2 weeks.",
    read: false,
    createdAt: new Date('2024-12-26'),
    link: '/team/hermawan',
  },
  {
    id: 'notif-2',
    type: 'success',
    title: 'Assessment Completed',
    message: 'Member Portal Authentication Upgrade assessment has been completed.',
    read: true,
    createdAt: new Date('2024-12-20'),
    link: '/assessments/assess-1',
  },
  {
    id: 'notif-3',
    type: 'info',
    title: 'New Team Member',
    message: 'Sarah Johnson has joined the Authentication Team.',
    read: true,
    createdAt: new Date('2024-12-18'),
  },
];

// Complete Assessment Result (for detail view)
export const sampleAssessmentResult: AssessmentResult = {
  assessment: assessments[0],
  historicalMatches,
  selectedMatchIds: ['hist-1', 'hist-2'],
  functionalModules,
  technicalModules,
  effortEstimation,
  jiraStories,
  codeImpacts,
  risks,
  dependencies,
};

// Helper function to get assessment by ID
export function getAssessmentById(id: string): Assessment | undefined {
  return assessments.find(a => a.id === id);
}

// Helper function to get ongoing assessments
export function getOngoingAssessments(): Assessment[] {
  return assessments.filter(a => a.status === 'analyzing' || a.status === 'draft');
}

// Helper function to get completed assessments
export function getCompletedAssessments(): Assessment[] {
  return assessments.filter(a => a.status === 'completed');
}
